apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        images: dangtong/node-app:08387b6aae1c438028fc937644d8d9d01607d482
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
